language: go

go:
- master
- 1.x
- 1.5.x
- 1.6.x
- 1.7.x
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x

go_import_path: github.com/kamilsk/retry/v3

sudo: false

before_install:
- export GO15VENDOREXPERIMENT=1
- export GO111MODULE=on

script:
- make test ARGS='-timeout=1s'

after_success:
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG
- if [[ $TRAVIS_GO_VERSION == 1.11* ]] && [ -n "$TRAVIS_TAG" ]; then curl -sL https://git.io/goreleaser | bash; fi

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/63f69d732d88862909a2
    on_success: change
    on_failure: always
    on_start:   never
