language: go

go:
- master
- 1.x
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x

sudo: false

script:
- make test

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/63f69d732d88862909a2
    on_success: change
    on_failure: always
    on_start:   never
